defmodule BlocksterV2Web.Endpoint do
  use Phoenix.Endpoint, otp_app: :blockster_v2

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  # Session cookie persists for 30 days so users stay logged in on mobile
  @session_options [
    store: :cookie,
    key: "_blockster_v2_key",
    signing_salt: "5Zxg0YVm",
    same_site: "Lax",
    max_age: 30 * 24 * 60 * 60
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  #
  # Cache headers:
  # - Production: assets/ files (with digest in filename): cache for 1 year (immutable)
  # - Development: short cache so Tailwind CSS changes are picked up immediately
  # - Other static files: cache for 1 hour with revalidation
  plug Plug.Static,
    at: "/",
    from: :blockster_v2,
    gzip: not code_reloading?,
    only: BlocksterV2Web.static_paths(),
    headers:
      if(code_reloading?,
        do: %{"cache-control" => "public, max-age=0, must-revalidate"},
        else: %{"cache-control" => "public, max-age=31536000, immutable"}
      ),
    only_matching: ~w(assets)

  plug Plug.Static,
    at: "/",
    from: :blockster_v2,
    gzip: not code_reloading?,
    only: BlocksterV2Web.static_paths(),
    headers: %{
      "cache-control" => "public, max-age=3600, must-revalidate"
    }

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :blockster_v2
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug BlocksterV2Web.Router
end
