import Config

# Mark environment for conditional logic in application.ex
config :high_rollers, :env, :dev

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
#
# NOTE: Blockster V2 uses ports 4000 and 4001, so we use 4002 and 4003
config :high_rollers, HighRollersWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4002],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "6jgjxuykAeZ682j7FJIfi4L/EBQKlkCEttCUWAPg+2ACcWSy13BT0EPqwnFAhTD1",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:high_rollers, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:high_rollers, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :high_rollers, HighRollersWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/high_rollers_web/router\.ex$",
      ~r"lib/high_rollers_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :high_rollers, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Load secrets from environment (set via .env file or shell)
config :high_rollers,
  admin_private_key: System.get_env("ADMIN_PRIVATE_KEY"),
  affiliate_linker_private_key: System.get_env("AFFILIATE_LINKER_PRIVATE_KEY"),
  default_affiliate: System.get_env("DEFAULT_AFFILIATE") || "0x0000000000000000000000000000000000000000"
